version: '3.8'

services:
  backend:
    image: kimhyeokil/back:latest
    container_name: back
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "9002:8080"
    networks:
      - jenkins-network

# Docker volume 정의
networks:
  jenkins-network:
    external: true


