spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB 드라이버
    url: jdbc:mysql://localhost:3306/perfectfit?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # 데이터베이스 URL
    username : ssafy
    password : ssafy

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false                   # 하이버네이트가 실행한 SQL을 출력할 때 보기 좋게 정렬
        use_sql_comments: true
        show_sql: true                     # 하이버네이트가 실행한 SQL을 출력
        jdbc:
          batch_size: 100                  #   insert/update 쿼리를 원하는 개수만큼 모아서 DB에 날릴 수 있는 옵션
        default_batch_fetch_size: 100
#      ddl-auto: create-drop                # ddl 자동 작성 여부
  # data_테이블명.sql 관련 실행 setting
  sql:
    init:
      mode: always
      data-locations:
        - 'classpath:/data_member.sql'
  # NoSQL setting
  data:
    # Redis setting
    redis:
      host: localhost
      port: 6379

# jwt setting
jwt:
  secret-key:
    access: 612834t213b497d23d94h2374693471269477h9qf87weonm8urcnhrnh8723y4n83294j93278queue8wqhrowrlsdhf7842298347r2y3er87y3wdhsaduh2398eyue8ue8dwidjasd938ue8dj12
    refresh: 612834t213b497d23d94h2374693471269477h9qf87weonm8urcnhrnh8723y4n83294j93278queue8wqhrowrlsdhf7842298347r2y3er87y3wdhsaduh2398eyue8ue8dwidjasd938ue8dj12

  expired-min:
    access: 60   # 액세스 토큰 만료제한시간 60분 (1시간) (60)
    refresh: 10080  # 리프레쉬 토큰 만료제한시간 10080분 (7일) (10080)

oauth:
  kakao:
    client-id: df089f203219a3b6f8b59089d4381d02
    client-secret: w3dHiDuDOiluFi2vjWpzSo1BbBhTnvpu
    redirect-uri: http://localhost:5173/member/loading/kakao
#    redirect-uri: http://localhost:8080/member/kakao
    scope:
      - profile_nickname
      - profile_image
      - account_email

  naver:
    client-id: tzXmova1GZfX43ujVeQU
    client-secret: 3BfuMlsrSV
    redirect_uri: http://localhost:5173/member/loading/naver
    scope:
      - nickname
      - email
      - profile_image

youtube:
  api:
    key: AIzaSyDqnJkym6OA2vJAasKGP8gjsP4sOwMZfxo